import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { Button, Navbar, Stack, Tooltip } from '@mantine/core'
import { Main } from 'src/components/Main';


const NAV_ITEMS = [
  {href: "/", label: "Index"},
  {href: "/dashboard", label: "Dashboard"},
];

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
      {NAV_ITEMS.map(item => {
        return (
          <Link href={item.href} className={styles.link}>
            {item.label}
          </Link>
        );
      })
      }
      </header>

      <Main page="index" inter={inter} />
    </>
  )
}
